apiVersion: v1
kind: Pod
metadata:
  name: nvim
spec:
  containers:
    - image: localhost/nvim:0.1.0
      name: nvim
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsGroup: 1001
        runAsUser: 1001
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /home/dev/projects
          name: projects
  restartPolicy: Never
  volumes:
    - hostPath:
        path: ${ROOT_DIR}/volumes/projects
        type: DirectoryOrCreate
      name: projects
